FROM r-base:3.6.3

ENV RENV_VERSION 0.12.3

COPY r_script.R /code/

RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}')"
RUN R -e "renv::install('here', 'ggplot2', 'mice', 'dplyr')"
CMD ["r", "/code/r_script.R"]
